vars: {
  d2-config: {
    pad: 24
    layout-engine: elk
  }
}
style: {
  fill: "#282C33"
}
classes: {
  box: {
    style: {
      fill: "#282C33"
      stroke: "#ABB2BF"
      font-color: "#FFFFFF"
      font: mono
      font-size: 18
      border-radius: 0
      stroke-width: 1
    }
  }
  core: {
    style: {
      fill: "#3A2F42"
      stroke: "#C778DD"
      font-color: "#FFFFFF"
      font: mono
      font-size: 18
      bold: true
      border-radius: 0
      stroke-width: 2
    }
  }
  io: {
    style: {
      fill: "transparent"
      stroke: "#ABB2BF"
      stroke-dash: 4
      font-color: "#ABB2BF"
      font: mono
      font-size: 16
      border-radius: 0
    }
  }
  db: {
    shape: cylinder
    style: {
      fill: "#282C33"
      stroke: "#C778DD"
      font-color: "#FFFFFF"
      font: mono
      font-size: 16
    }
  }
  note: {
    shape: text
    style: {
      font-color: "#ABB2BF"
      font: mono
      font-size: 14
    }
  }
  group: {
    style: {
      fill: "transparent"
      stroke: "#C778DD"
      stroke-dash: 5
      font-color: "#C778DD"
      font: mono
      font-size: 16
      border-radius: 0
    }
  }
  flow: {
    style: {
      stroke: "#C778DD"
      font-color: "#ABB2BF"
      font: mono
      font-size: 13
      stroke-width: 2
    }
  }
}
